<?php

return [
    'adminEmail' => 'admin@example.com',
    'uploadImages' => '/img_temporales/',
    'google_key' => 'AIzaSyCWmnu8hgRqQzEIU3Sp35ygYoyq_WOIC6Q',
    'metros_redonda' => 6000, //6km
    'metros_redonda_movil' => 12500, //6km
    'metros_redonda_visita' => 100,
    'api_utim' => 'http://utimedical.geomonitoreo.com/api/',
    'traccar' => array(	'socket_url' => 'ws://23.239.19.165:8082/api/socket',
    					'rest_url' => 'http://23.239.19.165:8082/api/',
    					'transmision_url' => 'http://23.239.19.165:5055/api',
    					'usuario' => 'geoadmin1',
    					'clave' => '@AbitGeo1server2017',
    ),
    'token_firebase' => 'AIzaSyDkLPjdNxx6V09ZUJr8yBSO-EqykywlFHw',
    'mensajes_push'=> [ 
                        'atencion_doctor_asignado' => 'Su atención fue aprobada, se le asignó un médico',
                        'atencion_doctor_llega' => 'El doctor ha llegado, salga a recibirlo',
                        'atencion_calificacion' => 'Califique la atención que recibio',
                        'atencion_realizar_pago' => 'Por favor realice el pago de la atención recibida',
                        'doctor_cuenta_activada' => 'Estimado Dr(a). su cuenta a sido activada, ya puede ingresar en UTIM APP',
                        'doctor_atencion_asignada' => 'Estimado Dr(a). se le asignó una atención, revisar UTIM APP',
                        'paciente_cancela_atencion' => 'Estimado Dr(a). La atención fue cancelada',
                    ],
    'url_api_evolution' => 'http:///181.188.208.19:8089/api/',
    'placetopay' => [
                        'login' => '54152e4a47cf5b4dc744d2a5992cc23c',
                        'secretKey' => 'Kcp8dH6G34w1bHq9',
                        'placetopay_url' => 'https://test.placetopay.ec/redirection/',
                        'iva' => 1.12,
                    ],
    'terminos_condiciones' => '<h2>1. Antecedentes.-</h2> 
        <p>UTIM es una persona jurídica debidamente constituida bajo las leyes de la República del Ecuador, inscrita, registrada y reconocida como tal, especializada en brindar servicios de atención medica pre hospitalaria, debidamente regulada y autorizada por las autoridades competentes.</p> 
        <h2>2. Objeto.-</h2>
        <p>Los presentes Términos y Condiciones regulan el uso de la aplicación informática de UTIM a quien en adelante será denominada la "Aplicación" y uso del sitio web www.utimutim.com a quien en adelante será denominado el "Sitio Web", cuya propiedad es de UTIMEDICAL S.A. con RUC: 1790737527001 con domicilio en la ciudad de Quito – Ecuador ubicada en la Av. Amazonas N33-215 y Alemania. 
        La Aplicación está dirigida exclusivamente a usuarios que residan en el Ecuador. Al acceder y utilizar esta Aplicación y Sitio Web el USUARIO reconoce que ha leído y aceptado estos Términos y Condiciones de Uso y se compromete a cumplir con las mismas. El Usuario reconoce y acepta que el uso y acceso a esta Aplicación y/o Sitio Web estará sujeto a las Condiciones de Uso que se encuentren en vigor en el momento en que acceda a la misma. UTIM se reserva el derecho de modificar en cualquier momento las presentes Condiciones de Uso, así como cualesquiera otras condiciones generales o particulares que resulten de la aplicación. El Usuario podrá notificar a UTIM a través de sus canales de Servicio al Cliente que no acepta cualquier eventual modificación de los presentes Términos y Condiciones de Uso. UTIM se reserva el derecho de interrumpir o suspender la Aplicación y/o el Sitio Web en cualquier momento.</p>
        <h2>3. Contenidos.-</h2>
        <p>A través de la Aplicación, UTIM facilita al Usuario los siguientes servicios:
        • Solicitud de asistencia médica pre hospitalaria a domicilio 
        • Rastreo satelital de la ruta a tomar del familiar relacionado en tiempo real
        La Aplicación y/o Sitio Web, facilita al Usuario el acceso a diversos contenidos, información y datos proporcionados por UTIM en relación con el Servicio (en adelante, los "Contenidos"). UTIM se reserva el derecho a modificar en cualquier momento la presentación, la configuración y ubicación de la Aplicación y/o el Sitio Web, así como los correspondientes términos de condiciones de acceso y uso. UTIM no garantiza que los Contenidos proporcionados a través de la Aplicación y/o Sitio Web serán en todo caso correctos, completos o actualizados.</p> 

        <h2>4. Acceso y uso.-</h2>
        <p>El acceso a la Aplicación estará limitado a usuarios mayores de 18 años. El Usuario (i) podrá autorizar a terceros a utilizar su cuenta únicamente bajo su responsabilidad. El usuario reconoce y acepta que el acceso y uso de la Aplicación y/o Sitio Web tiene lugar libre y conscientemente, bajo su exclusiva responsabilidad. UTIM no será en ningún caso responsable del uso que el Usuario y/o terceros pudieran hacer de la Aplicación y/o Sitio Web ni de los daños y perjuicios que pudieran derivarse del mismo. El Usuario se compromete a hacer un uso adecuado y lícito de la Aplicación y/o Sitio Web de conformidad con la legislación aplicable y las presentes Condiciones Generales de Uso, la moral y las buenas costumbres generalmente aceptadas, así como el orden público. El Usuario deberá abstenerse de (i) hacer un uso no autorizado o fraudulento de la Aplicación y/o Sitio Web; (ii) acceder o intentar acceder a recursos restringidos de la Aplicación y/o Sitio Web; (iii) utilizar la Aplicación y/o Sitio Web con fines o efectos ilícitos, ilegales, contrarios a lo establecido en las presentes Condiciones Generales de Uso, lesivos de los derechos e intereses de terceros, o que de cualquier forma puedan dañar, inutilizar o sobrecargar o impedir la normal utilización o disfrute de la Aplicación y/o Sitio Web; (iv) provocar daños en la Aplicación y/o Sitio Web o en los sistemas de sus proveedores o de terceros; (v) introducir o difundir virus informáticos o cualesquiera otros sistemas físicos o lógicos que sean susceptibles de provocar daños en los sistemas de UTIM, de sus proveedores o de terceros, (vi) intentar acceder, utilizar y/o manipular los datos de UTIM, terceros proveedores y otros usuarios; (vii) reproducir, copiar, distribuir, transformar o modificar los Contenidos, permitir el acceso a terceros a través de cualquier modalidad de comunicación pública, a menos que se cuente con la autorización del titular de los correspondientes derechos o ello esté legalmente permitido; (viii) obtener o intentar obtener los contenidos empleando para ello medios o procedimientos distintos de los que, según los casos, se hayan puesto a su disposición a este efecto. El Usuario únicamente podrá acceder a la Aplicación y/o Sitio Web a través de los medios autorizados. UTIM no será responsable en caso de que el Usuario no disponga de un dispositivo compatible o haya descargado una versión de la Aplicación incompatible con su dispositivo, ni del consumo de datos móviles ni recargos adicionales que podrían generarse a su plan de telefonía contratado por la utilización de la aplicación. A su vez UTIM no se responsabiliza por el rango de error de ubicación que pueda existir durante el uso de la aplicación (aproximadamente 10 mts). El registro de uso de la aplicación se encontrará disponible en el historial de la misma durante un tiempo aproximado de 2 meses y la actualización de ubicación en tiempo real se realizará cada 30 segundos aprox.</p>
        <h2>5. Condiciones adicionales para el acceso y uso.-</h2>
        <p>El acceso a la Aplicación estará sujeto en todo caso al previo registro del Usuario mediante el  cumplimiento del correspondiente formulario ("Formulario de Registro"), que será previamente facilitado al Usuario. UTIM se reserva el derecho de aceptar o rechazar libremente la solicitud de registro por parte del Usuario. Los datos introducidos por el Usuario en el Formulario de Registro deberán ser exactos, actuales y veraces en todo momento. El acceso y uso de la Aplicación o del área específica del Sitio Web estará sujeto un código asignado al Usuario por UTIM al rellenar el Formulario de Registro y el acceso se reputará realizado por dicho Usuario, quien responderá en todo caso de tal acceso y uso. El Usuario será responsable en todo momento de la custodia de su contraseña, asumiendo, en consecuencia, cualesquier daño y perjuicio que pudieran derivarse de su uso indebido, así como de la cesión, revelación o extravío de la misma. En caso de olvido de la contraseña o cualquier otra circunstancia que suponga un riesgo de acceso y/o utilización por parte de terceros no autorizados, el Usuario lo comunicará inmediatamente a UTIM a fin de que éste proceda al bloqueo y sustitución de la misma. En todo caso, cualesquier operación realizada antes de dicha comunicación se considerarán efectuadas por el Usuario, quien será responsable y pagará los gastos y/o daños que se deriven de cualquier acceso y/o uso no autorizado que se realice con anterioridad a dicha comunicación.
        Este Acuerdo no constituye una venta y no le transmite ningún derecho de propiedad sobre la aplicación. El nombre de UTIM, su logotipo, los nombres de productos y logotipos asociados con la aplicación son marcas registradas de UTIM, sus compañías afiliadas o terceros, y no se concede ningún derecho de licencia para su uso.</p>  
        <h2>6. Derechos de propiedad intelectual e industrial.-</h2>
        <p>El Usuario reconoce y acepta que todos los derechos de propiedad intelectual e industrial sobre los contenidos y/o cualesquier otros elementos insertados en la Aplicación y/o Sitio Web (incluyendo, sin limitación, marcas, logotipos, nombres comerciales, textos, imágenes, gráficos, diseños, sonidos, bases de datos, software, diagramas de flujo, presentación, audio y vídeo), pertenecen a UTIM y a sus empresas afiliadas. UTIM autoriza al Usuario a utilizar, visualizar, imprimir, descargar y almacenar los contenidos y/o los elementos insertados en la Aplicación y/o Sitio Web exclusivamente para su uso personal, privado y no lucrativo, absteniéndose de realizar sobre los mismos cualquier acto de descompilación, ingeniería inversa, modificación, divulgación o suministro. Cualquier otro uso o explotación de cualesquier contenido y/u otros elementos insertados en la Aplicación y/o Sitio Web distinto de los aquí expresamente previstos, estará sujeto a la autorización previa de UTIM.</p>
        <h2>7. Protección de datos.-</h2>
        <p>Los datos personales (en lo sucesivo, los Datos) que el Usuario proporciona por medio del Formulario de Registro se integrarán en un fichero de datos personales del que es responsabilidad de UTIM.</p>
        <h2>8. Exclusión de garantías y responsabilidad.-</h2>
        <p>UTIM no garantiza la disponibilidad y continuidad del funcionamiento de la Aplicación y/o Sitio Web. En consecuencia, UTIM no será en ningún caso responsable por cualesquier daño y perjuicio que puedan derivarse de (i) la falta de disponibilidad o accesibilidad a la Aplicación y/o Sitio Web; (ii) la interrupción en el funcionamiento de la Aplicación y/o Sitio Web o fallos informáticos, averías telefónicas, desconexiones, retrasos o bloqueos causados por deficiencias o sobrecargas en las líneas telefónicas, centros de datos, en el sistema de Internet o en otros sistemas electrónicos, producidos en el curso de su funcionamiento; y (iii) otros daños que puedan ser causados por terceros mediante intromisiones no autorizadas ajenas al control de UTIM., UTIM pone a disposición del Usuario el Centro de atención de Call Center al 023814950 en el que el Usuario podrá solicitar  a UTIM servicios y requerimientos,UTIM no garantiza la ausencia de virus ni de otros elementos en la Aplicación y/o Sitio Web introducidos por terceros ajenos a UTIM que puedan producir alteraciones en los sistemas físicos o lógicos del Usuario o en los documentos electrónicos y ficheros almacenados en sus sistemas. UTIM adopta diversas medidas de protección para proteger la Aplicación y/o Sitio Web y los contenidos contra ataques informáticos de terceros. No obstante, UTIM no garantiza que terceros no autorizados no puedan conocer las condiciones, características y circunstancias en las cuales el Usuario accede a la Aplicación y/o Sitio Web. En consecuencia, UTIM no será en ningún caso responsable de los daños y perjuicios que pudieran derivarse de dicho acceso no autorizado. Con la suscripción de las presentes Condiciones Generales de Uso, el Usuario declara que mantendrá indemne frente a cualquier reclamación a UTIM, su sociedad matriz, directores, socios, empleados, abogados y agentes derivadas del (i) incumplimiento por parte del Usuario de cualquier disposición contenida las presentes Condiciones Generales de Uso o de cualquier ley o regulación aplicable a las mismas, (ii) incumplimiento o violación de los derechos de terceros incluyendo, a título meramente enunciativo; (iii) cualquier daño o perjuicio causado por el Usuario en el uso del Servicio a un tercero y (iv) incumplimiento del uso permitido de la Aplicación y/o Sitio WebUTIM. </p>
        <h2>9. Notificaciones.-</h2>
        <p>UTIM podrá realizar las notificaciones oportunas a través de una notificación general en la Aplicación, a través de la dirección de correo electrónico facilitada por el Usuario en el Formulario de Registro, mediante SMS, o a través de correo ordinario a la dirección facilitada por el Usuario en el Formulario de Registro. El Usuario, a su vez podrá cursar notificaciones a UTIM a través de los Canales de Servicio al Cliente.</p>
        <h2>10. Cesión.-</h2>
        <p>El Usuario no podrá ceder los derechos y obligaciones asumidos en las presentes Condiciones Generales de Uso sin el previo consentimiento escrito presentado a UTIM. UTIM podrá ceder, sin necesidad de recabar el consentimiento previo del Usuario, las presentes Condiciones Generales de Uso a cualquier entidad comprendida dentro de su grupo de sociedades, en todo el mundo, así como a cualquier persona o entidad que le suceda en el ejercicio de su negocio por cualesquiera títulos.</p>
        <h2>11. Ley aplicable y Jurisdicción</h2>
        <p>Los presentes Términos y Condiciones de Uso, así como la relación entre UTIM y el Usuario, se regirán bajo la legislación de la República del Ecuador. Toda controversia o diferencia que surja sobre el sentido o alcance de las disposiciones de este contrato o en caso de incumplimiento, las partes dejan expresa constancia de que renuncian domicilio y aceptan que toda diferencia o inconveniente derivado de este contrato, a requerimiento de cualquiera de las partes, sea resuelta con la asistencia de  un mediador calificado del Centro de Arbitraje y Mediación de la Cámara de Comercio de Quito. En el evento de no resolver las diferencias, las partes se someten a un Arbitrario, de conformidad con el trámite previsto en la Ley de Arbitraje y Mediación, al Reglamento del Centro de Arbitraje y Mediación de la Cámara de Comercio de Quito, relativa a, o que tenga relación con este contrato, será resuelta por un tribunal arbitral del Centro de Arbitraje y Mediación de la Cámara de Comercio de Quito, que se sujetará a lo dispuesto en la Ley de Arbitraje y Mediación, el Reglamento de dicho Centro y las siguientes normas: " El tribunal estará integrado por un árbitro designado conforme el Reglamento del Centro; " El tribunal decidirá en derecho; " Para la ejecución de medidas cautelares, el tribunal arbitral está facultado para solicitar a los funcionarios públicos, judiciales, policiales y administrativos su cumplimiento sin que sea necesario el recurrir a juez ordinario alguno; " </p>

        <p>En el caso de controversia sobre el sentido o alcance de las disposiciones de este contrato o en caso de incumplimiento, las partes dejan expresa constancia de que renuncian domicilio y aceptan que toda diferencia o inconveniente derivado de este contrato, a requerimiento de cualquiera de las partes, sea resuelta con la asistencia de  un mediador calificado del Centro de Arbitraje y Mediación de la Cámara de Comercio de Quito, En el evento de no resolver las diferencias, las partes se someten a un Arbitrario, de conformidad con el trámite previsto en la Ley de Arbitraje y Mediación, al Reglamento del Centro de Arbitraje y Mediación de la Cámara de Comercio de Quito, y a las siguientes normas:
        Las partes se obligan a acatar el laudo arbitral que se expida, el cual deberá fundarse en derecho y se comprometen a no interponer ningún tipo de recurso contra del laudo arbitral. Será un solo Árbitro el que conozca de la presenta controversia, quien tendrá su respectivo alterno. Tanto el Árbitro como su alterno serán elegidos por sorteo. Para la ejecución de las medidas cautelares, tanto el Arbitro como su alterno están facultados para solicitar el auxilio de funcionarios público, judiciales, policiales y administrativos, sin que sea necesario acudir a Juez ordinario alguno. Los costos, gastos y honorarios profesionales que generan este procedimiento arbitral será cubierto en partes iguales; el lugar del arbitraje será en la ciudad de Quito, en las instalaciones del Centro de Arbitraje y Mediación de la Cámara de Comercio de Quito. El procedimiento arbitral será confidencial.</p>',
];
